on: [push]

jobs:
  cognition-deploy:
    runs-on: ubuntu-latest
    name: Deploy experiment to Cognition
    steps:
      - uses: actions/checkout@v3
      - uses: javidalpe/cognition-deploy-action@v1.2.0
        id: deploy
        with:
          repository: jspsych
          personal-access-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          path: scripts/backward-digit-span
      - run: echo "The public link to the task is ${{ steps.deploy.outputs.link }}"
